[project]
name = "middleware"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vrushabh Damle", email = "dwrushabh@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.4.2",
    "langchain-openai>=1.6.2",
]

[project.scripts]
middleware = "middleware:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
