[project]
name = "02-session-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vrushabh Damle", email = "dwrushabh@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
02-session-mcp = "02_session_mcp:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
